### ISSUE TITLE
Sending Files Hangs in Monterey

### ISSUE THREAD

**Issue by eliellis** [airmessage/airmessage-server-next#1]
Hi, awesome work with AirMessage! Just wanted to open an issue for this since it's just come up for me after upgrading macOS...

It seems that while AirMessage server is perfectly functional sending plain text messages, while sending files, the message in question just endlessly hangs until eventually getting a "Failed to Send" error from iMessage. It appears this [may already be known](https://apple.stackexchange.com/questions/429586/applescript-messages-app-monterey-problem) but wanted to let the author know that AirMessage is impacted. 

My solution for now is just to downgrade macOS to Big Sur.

**Comment by tagavari** [comment]
Thank you for bringing this up! This issue is present in [AirMessage Server 3](https://github.com/airmessage/airmessage-server-legacy), though it's been resolved in AirMessage Server 4 (this repo).

If you want to try running this version, you can download a build from [releases](https://github.com/airmessage/airmessage-server-next/releases) (though if you're using the Android app as well, make sure you're running a beta version)
